### ISSUE TITLE
/nban doesnt kick

### ISSUE THREAD

**Issue by dries-c** [LegendOfMCPE/Hormones#23] opened 2017-07-30 16:20 UTC
Do /nban and the player ist kicked

**Comment by Driesboy** [comment] 2017-07-30 16:22
And his name is in the database
![image](https://user-images.githubusercontent.com/15795262/28755137-0b92ef4c-7554-11e7-901f-5f4d4ee752ad.jpg)

**Comment by dries-c** [comment] 2017-07-30 16:27
and he still can join

**Comment by SOF3** [comment] 2017-07-30 16:30
Is the last arterial ID in `/hormones` changed?

**Comment by dries-c** [comment] 2017-07-30 16:31
since??

**Comment by dries-c** [comment] 2017-07-30 16:39
2017-07-30 [17:38:27] [Server thread/INFO]: You are on a hub server: gamecraftpe.tk:19132 (gamecraftpe.tk:19132)
2017-07-30 [17:38:27] [Server thread/INFO]: Organic status: 1 / 50 in 1 servers
2017-07-30 [17:38:27] [Server thread/INFO]: Network status: 1 / 50 in 1 servers
2017-07-30 [17:38:27] [Server thread/INFO]: Recommended alt server: N/A
2017-07-30 [17:38:27] [Server thread/INFO]: Vein up time (s): 0.035001993179321
2017-07-30 [17:38:27] [Server thread/INFO]: Artery net time (s): NAN
2017-07-30 [17:38:27] [Server thread/INFO]: Artery cycle time (s): 0.049952857494354
2017-07-30 [17:38:27] [Server thread/INFO]: Lymph net time (s): 0.00068004608154297
2017-07-30 [17:38:27] [Server thread/INFO]: Lymph cycle time (s): 0.049932861328125
2017-07-30 [17:38:27] [Server thread/INFO]: Last arterial hormone ID: 23332
2017-07-30 [17:38:28] [Server thread/INFO]: Abdarhman11[/78.95.221.131:1631] logged out due to We are working on our servers!
2017-07-30 [17:38:28] [Server thread/INFO]: sagad_al_khaldy[/37.238.206.34:26188] logged out due to We are working on our servers!
2017-07-30 [17:38:36] [Server thread/INFO]: NaturalRaptor71[/46.43.126.202:59893] logged out due to We are working on our servers!
2017-07-30 [17:38:37] [Server thread/INFO]: Driesboy @ 192.168.0.1 have been banned by CONSOLE for 7 days: "hacks". He/She have to wait for 7 days more before he/she can join.
2017-07-30 [17:38:38] [Server thread/INFO]: loooooo[/92.98.233.98:54547] logged out due to We are working on our servers!
2017-07-30 [17:38:42] [Server thread/INFO]: Driesboy[/192.168.0.1:2943] logged out due to Kicked by admin.
2017-07-30 [17:38:42] [Server thread/INFO]: [CONSOLE: Kicked Driesboy from the game]
2017-07-30 [17:38:44] [Server thread/INFO]: Rami_Ender[/78.191.112.186:54182] logged out due to We are working on our servers!
2017-07-30 [17:38:44] [Server thread/INFO]: Using Hormones v2.0.3 by SOFe
2017-07-30 [17:38:44] [Server thread/INFO]: You are on a hub server: gamecraftpe.tk:19132 (gamecraftpe.tk:19132)
2017-07-30 [17:38:44] [Server thread/INFO]: Organic status: 0 / 50 in 1 servers
2017-07-30 [17:38:44] [Server thread/INFO]: Network status: 0 / 50 in 1 servers
2017-07-30 [17:38:44] [Server thread/INFO]: Recommended alt server: N/A
2017-07-30 [17:38:44] [Server thread/INFO]: Vein up time (s): 0.027001778284709
2017-07-30 [17:38:44] [Server thread/INFO]: Artery net time (s): NAN
2017-07-30 [17:38:44] [Server thread/INFO]: Artery cycle time (s): 0.04988285779953
2017-07-30 [17:38:44] [Server thread/INFO]: Lymph net time (s): 0.00078004598617554
2017-07-30 [17:38:44] [Server thread/INFO]: Lymph cycle time (s): 0.049922852516174
2017-07-30 [17:38:44] [Server thread/INFO]: Last arterial hormone ID: 23332

**Comment by SOF3** [comment] 2017-07-31 03:59
Very likely to be the same issue with #24. Marking as duplicate right now.

**Comment by SOF3** [comment] 2017-07-31 04:00
Likely to be duplicate of #24.

**Closed as completed by SOF3** 2017-07-31 03:59 UTC
Labels: duplicate
